# You can copy and paste this template into a new `.gitlab-ci.yml` file.
# You should not add this template to an existing `.gitlab-ci.yml` file by using the `include:` keyword.
#
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Flutter.gitlab-ci.yml
variables:
  # Note: use specific tags as docker images may not always be pulled due to "if-not-present" pull policy.
  #       Thus, do not use tags like latest/beta, but check https://hub.docker.com/_/dart?tab=tags for latest.
  DART_VERSION: '2.18.6'

# code_quality:
#   stage: test
#   image: "cirrusci/flutter:1.22.5"
#   before_script:
#     - pub global activate dart_code_metrics
#     - export PATH="$PATH:$HOME/.pub-cache/bin"
#   script:
#     - metrics lib -r codeclimate  > gl-code-quality-report.json
#   artifacts:
#     reports:
#       codequality: gl-code-quality-report.json

# test:
#   stage: test
#   image: "cirrusci/flutter:1.22.5"
#   before_script:
#     - flutter channel master
#     - flutter upgrade
#     - flutter pub global activate junitreport
#     - export PATH="$PATH:$HOME/.pub-cache/bin"
#   script:
#     - flutter test --machine --coverage | tojunit -o report.xml
#     - lcov --summary coverage/lcov.info
#     - genhtml coverage/lcov.info --output=coverage
#   coverage: '/lines\.*: \d+\.\d+\%/'
#   artifacts:
#     name: coverage
#     paths:
#       - $CI_PROJECT_DIR/coverage
#     reports:
#       junit: report.xml

test:
  image: cirrusci/flutter:stable
  script:
    - flutter doctor
    - flutter pub get
    - flutter clean
    - flutter test --coverage
    - lcov --summary coverage/lcov.info

test_drive:
  image: registry.gitlab.com/endrilickollari/flutter_test_app
  script:
    - /app/chromedriver --whitelisted-ips --port=4444 &
    - flutter doctor
    - flutter pub get
    - flutter clean
    - flutter drive --target=test_driver/app.dart --release
